### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by cmmaio** [zzyyyl/zzyyyl#1]
This is regarding the MAA arknights tool can you tell me how to set up the timer function so it automatically does the tasks every 6 hours? I fiddled around with it but cant seem to get it to work properly thanks!

**Comment by cmmaio** [comment]
Quite inconvenient they not having a discord server for the MAA tool...

**Comment by zzyyyl** [comment]
Sorry for being late. Maybe you can try something like this:

![image](https://github.com/user-attachments/assets/24ae0e49-e17e-45b5-bbaa-63550392c71d)

MAA's README (https://maa.plus/docs/en-us/#advertisement) shows QQ group (mainly for Chinese users) and telegram group.

**Comment by cmmaio** [comment]
hm yea i was just confused by what format the timers are in. is 1234 am and 5678 pm? or do they use 24hr time etc 
would the image above be 12 am, 6 am 12 pm 6pm?

**Comment by zzyyyl** [comment]
> hm yea i was just confused by what format the timers are in. is 1234 am and 5678 pm? or do they use 24hr time etc would the image above be 12 am, 6 am 12 pm 6pm?

yeah, it's 24hr time
